### ISSUE TITLE
Issues with Link operationIds

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/microsoft-graph-explorer-api#271]
Works for nav properties to an entity

Doesn't work for nav properties to an entity collection
applications.GetExtensionProperties is generated but should be applications.ListExtensionProperties

```
appDefinitions:
              operationId: appCatalogs.teamsApps.GetAppDefinitions
              parameters:
                teamsApp-id: $request.path.teamsApp-id
                teamsAppDefinition-id: $response.body#/id
```
This second parameter is not invalid and not needed.
